name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create releases and push tags
      issues: write # To create release notes
      pull-requests: write # To create release notes

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required by semantic-release to get all commits

      - name: Python Semantic Release
        uses: "python-semantic-release/python-semantic-release@v10.2.0"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: true

      - name: cache dist/ artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: load cached artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
