name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create releases and push tags
      issues: write # To create release notes
      pull-requests: write # To create release notes

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required by semantic-release to get all commits

      - name: Python Semantic Release
        uses: "python-semantic-release/python-semantic-release@v10.2.0"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: true
